version: '2'
services:
  moissoncatalogue-app:
    image: moissoncatalogue
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://moissoncatalogue-postgresql:5432/moissoncatalogue
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://moissoncatalogue-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://moissoncatalogue-elasticsearch:9200
    ports:
      - 8080:8080
  moissoncatalogue-postgresql:
    extends:
      file: postgresql.yml
      service: moissoncatalogue-postgresql
  moissoncatalogue-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: moissoncatalogue-elasticsearch
